apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-todo
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
        - name: flask-todo
          image: flask-todo-app:latest  # Use the image we will build
          imagePullPolicy: Never  # Prevent pulling from Docker Hub
          env:
            - name: DATABASE_URI
              value: "mysql+mysqlconnector://flaskuser:flaskpassword@mysql-service/flask_todo_db"
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-todo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
