version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: flask_todo_db
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  flaskapp:
    build: .
    container_name: flask_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URI: "mysql+mysqlconnector://flaskuser:flaskpassword@db/flask_todo_db"

volumes:
  mysql_data:
