# name: Destroy Infrastructure

# on:
#   workflow_dispatch:  # allows manual trigger from GitHub UI

# jobs:
#   destroy:
#     runs-on: ubuntu-latest

#     env:
#       AWS_REGION: us-east-1
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.5.0  # use your version

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Destroy
#         run: terraform destroy -auto-approve